services:
  - type: web
    name: cyril-pdf-renderer
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: LOG_BROWSER_CONSOLE
        value: true
      - key: LOG_REQUESTS
        value: true
      - key: DEFAULT_TIMEOUT_MS
        value: 120000
      - key: DEFAULT_WAIT_FOR_NETWORK_IDLE_MS
        value: 1500
      - key: DEFAULT_WAIT_FOR_DOM_STABLE_MS
        value: 1500
      - key: API_KEY
        sync: false
